# Generated by Django 2.1.7 on 2019-03-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20190330_0354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_work_this_obj', 'Work this obj'),)},
        ),
    ]
