# Generated by Django 2.1.7 on 2019-03-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190330_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_work_this_obj', 'Work this obj. Permission set Admin'), ('can_work_this_obj_sometime', 'Work this obj. Permission set User'))},
        ),
    ]
