# Generated by Django 2.1.7 on 2019-04-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('todo', '0008_auto_20190331_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.ManyToManyField(blank=True, help_text='access to company data', related_name='Tokens', to='authtoken.Token'),
        ),
    ]
