# Generated by Django 2.1.7 on 2019-04-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_company_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': (('can_work_this_obj', 'Work this obj. Set permission Admin'),)},
        ),
    ]
